[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-dotenv",
    "sqlalchemy",
    "sqlmodel",
    "google-auth",
    "google-auth-oauthlib",
    "google-api-python-client",
    "python-multipart",
    "httpx",
    "pydantic",
    "pydantic-settings",
    "aiofiles",
    "celery",
    "redis",
    "aiosqlite",
]

